global:
    api-listen-addr: :5183
    timeout: 10s
    memo: ""
    light-cache-size: 20
    log-level: ""
    ics20-memo-limit: 0
    max-receiver-size: 0
chains:
    atom:
        type: cosmos
        value:
            key-directory: /home/nimda/.relayer/keys/cosmoshub-testnet
            key: test2
            chain-id: cosmoshub-testnet
            rpc-addr: http://127.0.0.1:26658
            account-prefix: cosmos
            keyring-backend: test
            gas-adjustment: 1.8
            gas-prices: 0.5uatom
            min-gas-amount: 0
            max-gas-amount: 0
            debug: true
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: null
            signing-algorithm: ""
            broadcast-mode: batch
            min-loop-duration: 0s
            extension-options: []
            feegrants: null
    nucleus:
        type: cosmos
        value:
            key-directory: /home/nimda/.relayer/keys/nucleus-testnet
            key: test1
            chain-id: nucleus-testnet
            rpc-addr: http://127.0.0.1:26657
            account-prefix: nuc
            keyring-backend: test
            gas-adjustment: 1.8
            gas-prices: 0.5unucl
            min-gas-amount: 0
            max-gas-amount: 0
            debug: true
            timeout: 20s
            block-timeout: ""
            output-format: json
            sign-mode: direct
            extra-codecs: []
            coin-type: null
            signing-algorithm: ""
            broadcast-mode: batch
            min-loop-duration: 0s
            extension-options: []
            feegrants: null
paths:
    nucleus-atom:
        src:
            chain-id: nucleus-testnet
            client-id: 07-tendermint-1
            connection-id: connection-1
        dst:
            chain-id: cosmoshub-testnet
            client-id: 07-tendermint-1
            connection-id: connection-1
        src-channel-filter:
            rule: ""
            channel-list: []
